apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-flask

build:
  cluster:
    dockerConfig:
      secretName: kaniko-secret
  artifacts:
  - image: hello-flask

deploy:
  kubectl: {}

manifests:
  rawYaml:
     - deployment.yaml
